<?php
namespace Audit\V1\Tests;

use Audit\V1\AuditManager;
use PHPUnit\Framework\TestCase;

class AuditManagerTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    /**
     * Debug SKIPPED
     */
    public function testDebug()
    {
        $sut = new AuditManager();
        var_dump(realpath($sut->getDirectoryPath()));
        $this->markTestSkipped();
    }


    public function testConstructor()
    {
        $sut = new AuditManager();

        $this->assertEquals(3, $sut->getMaxEntriesPerFile());
        $this->assertEquals($sut->getDefaultDirectoryPath(), $sut->getDirectoryPath());
    }

    public function testConstructor_BadMaxEntriesPerFile()
    {
        $maxEntriesPerFile = -1;

        $this->expectException(\LogicException::class);
        $sut = new AuditManager($maxEntriesPerFile);
        var_dump($sut->getMaxEntriesPerFile());
    }

    public function testConstructor_BadDirectoryPath()
    {
        $maxEntriesPerFile = 3;
        $directoryPath = __DIR__."/foo";

        $this->expectException(\LogicException::class);
        $sut = new AuditManager($maxEntriesPerFile, $directoryPath);
        var_dump($sut->getDirectoryPath());
    }


}